export const featureProductData = [
  {
    id: "1",
    img: "https://rukminim2.flixcart.com/fk-p-flap/64/64/image/629b0a6f61037ae6.png?q=100",
    name: "TVs & Electronics",
    link: "",
    subNavigation: false,
  },
  {
    id: "2",
    img: "https://rukminim2.flixcart.com/fk-p-flap/64/64/image/f2802fac96dffea9.png?q=100",
    name: "Appliance",
    link: "",
    subNavigation: true,
  },
  {
    id: "3",
    img: "https://rukminim2.flixcart.com/fk-p-flap/64/64/image/74f0eb6cc10e2743.png?q=100",
    name: "Fashion",
    link: "",
    subNavigation: false,
  },
  {
    id: "4",
    img: "https://rukminim2.flixcart.com/fk-p-flap/64/64/image/f925cfe5ecdf6acf.png?q=100",
    name: "Beauty",
    link: "",
    subNavigation: true,
  },
  {
    id: "5",
    img: "https://rukminim2.flixcart.com/fk-p-flap/64/64/image/38d4fbb64c70a3ff.png?q=100",
    name: "Home & Kitchen ",
    link: "",
    subNavigation: true,
  },
  {
    id: "6",
    img: "https://rukminim2.flixcart.com/fk-p-flap/64/64/image/fef14e08ec83a6d7.png?q=100",
    name: "Furniture",
    link: "",
    subNavigation: false,
  },
  {
    id: "7",
    img: "https://rukminim2.flixcart.com/fk-p-flap/64/64/image/83de409bda2f3834.png?q=100",
    name: "Flights",
    link: "",
    subNavigation: false,
  },
  {
    id: "8",
    img: "https://rukminim2.flixcart.com/fk-p-flap/64/64/image/05d708653beff580.png?q=100",
    name: "Two Wheelers",
    link: "",
    subNavigation: false,
  },
  {
    id: "9",
    img: "https://rukminim2.flixcart.com/fk-p-flap/64/64/image/38a459d6d1fc930a.png?q=100",
    name: "Mobiles & Tablets",
    link: "",
    subNavigation: false,
  },
];
